[package]
name = "woodpecker-major"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
bitflags = "1.3.2"
dotenv = "0.15"
futures = "0.3.21"
once_cell = "1"
regex = "1.5.6"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "1.14.0", features = ["time_0_3"] }
thiserror = "1"
time = "0.3"
tokio = { version = "1.18" }
url = "2"

[dev-dependencies]
tokio = { version = "1.18", features = ["rt", "macros"] }

[features]
default = []
fireman = []
